namespace SalesSupportTool.Domain.Models.BuiltWithApi
{    public class SimpleDomainInfo
    {
        public string Postcode { get; set; }
        public string Id { get; set; }
        public int TechSpend { get; set; }
        public string Revenue { get; set; }
        public int Followers { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Sku { get; set; }
        public List<string> RootAds { get; set; }
        public List<string> RootWidgets { get; set; }
        public List<string> RootAnalytics { get; set; }
        public List<string> RootDocInfo { get; set; }
        public List<string> RootShop { get; set; }
        public List<string> RootFeeds { get; set; }
        public List<string> RootJavascript { get; set; }
        public List<string> RootCms { get; set; }
        public List<string> RootWebMaster { get; set; }
        public List<string> RootCdn { get; set; }
        public List<string> RootMedia { get; set; }
        public List<string> RootSeoHeaders { get; set; }
        public List<string> RootCdns { get; set; }
        public List<string> RootFramework { get; set; }
        public List<string> RootPayment { get; set; }
        public List<string> RootParked { get; set; }
        public List<string> RootEncoding { get; set; }
        public List<string> RootWebServer { get; set; }
        public List<string> RootMobile { get; set; }
        public List<string> RootMapping { get; set; }
        public List<string> RootServer { get; set; }
        public List<string> RootMx { get; set; }
        public List<string> RootSsl { get; set; }
        public List<string> RootLink { get; set; }
        public List<string> RootHosting { get; set; }
        public List<string> RootSeoTitle { get; set; }
        public List<string> RootSeoMeta { get; set; }
        public List<string> RootAgency { get; set; }
        public List<string> RootNs { get; set; }
        public List<string> RootShipping { get; set; }
        public List<string> RootLanguage { get; set; }
        public List<string> RootCopyright { get; set; }
        public List<string> RootRobots { get; set; }
        public List<string> RootRegistrar { get; set; }
        public List<string> AllAds { get; set; }
        public List<string> AllWidgets { get; set; }
        public List<string> AllAnalytics { get; set; }
        public List<string> AllDocInfo { get; set; }
        public List<string> AllShop { get; set; }
        public List<string> AllFeeds { get; set; }
        public List<string> AllJavascript { get; set; }
        public List<string> AllCms { get; set; }
        public List<string> AllWebMaster { get; set; }
        public List<string> AllCdn { get; set; }
        public List<string> AllMedia { get; set; }
        public List<string> AllSeoHeaders { get; set; }
        public List<string> AllCdns { get; set; }
        public List<string> AllFramework { get; set; }
        public List<string> AllPayment { get; set; }
        public List<string> AllParked { get; set; }
        public List<string> AllEncoding { get; set; }
        public List<string> AllWebServer { get; set; }
        public List<string> AllMobile { get; set; }
        public List<string> AllMapping { get; set; }
        public List<string> AllServer { get; set; }
        public List<string> AllMx { get; set; }
        public List<string> AllSsl { get; set; }
        public List<string> AllLink { get; set; }
        public List<string> AllHosting { get; set; }
        public List<string> AllSeoTitle { get; set; }
        public List<string> AllSeoMeta { get; set; }
        public List<string> AllAgency { get; set; }
        public List<string> AllNs { get; set; }
        public List<string> AllShipping { get; set; }
        public List<string> AllLanguage { get; set; }
        public List<string> AllCopyright { get; set; }
        public List<string> AllRobots { get; set; }
        public List<string> AllRegistrar { get; set; }
        public List<string> NonRootAds { get; set; }
        public List<string> NonRootWidgets { get; set; }
        public List<string> NonRootAnalytics { get; set; }
        public List<string> NonRootDocInfo { get; set; }
        public List<string> NonRootShop { get; set; }
        public List<string> NonRootFeeds { get; set; }
        public List<string> NonRootJavascript { get; set; }
        public List<string> NonRootCms { get; set; }
        public List<string> NonRootWebMaster { get; set; }
        public List<string> NonRootCdn { get; set; }
        public List<string> NonRootMedia { get; set; }
        public List<string> NonRootSeoHeaders { get; set; }
        public List<string> NonRootCdns { get; set; }
        public List<string> NonRootFramework { get; set; }
        public List<string> NonRootPayment { get; set; }
        public List<string> NonRootParked { get; set; }
        public List<string> NonRootEncoding { get; set; }
        public List<string> NonRootWebServer { get; set; }
        public List<string> NonRootMobile { get; set; }
        public List<string> NonRootMapping { get; set; }
        public List<string> NonRootServer { get; set; }
        public List<string> NonRootMx { get; set; }
        public List<string> NonRootSsl { get; set; }
        public List<string> NonRootLink { get; set; }
        public List<string> NonRootHosting { get; set; }
        public List<string> NonRootSeoTitle { get; set; }
        public List<string> NonRootSeoMeta { get; set; }
        public List<string> NonRootAgency { get; set; }
        public List<string> NonRootNs { get; set; }
        public List<string> NonRootShipping { get; set; }
        public List<string> NonRootLanguage { get; set; }
        public List<string> NonRootCopyright { get; set; }
        public List<string> NonRootRobots { get; set; }
        public List<string> NonRootRegistrar { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string LinkedIn { get; set; }
        public string YouTube { get; set; }
        public string Instagram { get; set; }
        public string Vimeo { get; set; }
    }
}